### ISSUE TITLE
Error after the speaker verification

### ISSUE THREAD

**Issue by Yuppich** [vivekuppal/transcribe#145]
Getting following error after the speaker verification: 

 Using Open AI Whisper API for transcription.
fatal: not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "C:\Users\Test\Desktop\transcribe-main\transcribe-main\app\transcribe\main.py", line 114, in <module>
    main()
  File "C:\Users\Test\Desktop\transcribe-main\transcribe-main\app\transcribe\main.py", line 51, in main
    handle_args_batch_tasks(args, global_vars)
  File "C:\Users\Test\Desktop\transcribe-main\transcribe-main\app\transcribe\args.py", line 90, in handle_args_batch_tasks
    interactions.params(args)
  File "C:\Users\Test\Desktop\transcribe-main\transcribe-main\app\transcribe\interactions.py", line 81, in params
    query_params = create_params(args)
                   ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Test\Desktop\transcribe-main\transcribe-main\app\transcribe\interactions.py", line 59, in create_params
    ps = detect_ps()
         ^^^^^^^^^^^
  File "C:\Users\Test\Desktop\transcribe-main\transcribe-main\app\transcribe\interactions.py", line 101, in detect_ps
    subprocess.check_output(["powershell", "-c", "whoami"])
  File "C:\Users\Test\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Test\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Test\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Test\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
Exception ignored in atexit callback: <function exit_params at 0x000001D61CB3EB60>
Traceback (most recent call last):
  File "C:\Users\Test\Desktop\transcribe-main\transcribe-main\app\transcribe\interactions.py", line 111, in exit_params
    query_params = create_params(args=None)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Test\Desktop\transcribe-main\transcribe-main\app\transcribe\interactions.py", line 59, in create_params
    ps = detect_ps()
         ^^^^^^^^^^^
  File "C:\Users\Test\Desktop\transcribe-main\transcribe-main\app\transcribe\interactions.py", line 101, in detect_ps
    subprocess.check_output(["powershell", "-c", "whoami"])
  File "C:\Users\Test\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Test\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Test\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Test\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by mang0sw33t** [comment]
Thanks for reporting the issue.
Confirm you are using the the released binaries.

**Comment by Yuppich** [comment]
> Thanks for reporting the issue. Confirm you are using the the released binaries.

Downloaded the latest repository and installed everything according to the guide. 
Python 3.11.7

**Comment by mang0sw33t** [comment]
Somehow application is not able to detect presence of PowerShell on the machine. Likely it is not in the path. 
PowerShell is used for downloading the models if required. 

Complete output from the command prompt is very helpful in detecting the correct errors. Add that to issues filed in the future.

**Comment by mang0sw33t** [comment]
what version of openai library is in use.
Can check using `pip -list`

I have these versions
```
openai                    1.3.5
openai-whisper            20231117
```

**Comment by Yuppich** [comment]
```
openai                    1.11.1
openai-whisper      20231117
```

**Comment by mang0sw33t** [comment]
I do not see this issue when using the library versions specified above.
Is the OpenAI key provided in override.yaml in this format
```
OpenAI:
  api_key: 'API_KEY'
```
Replace API_KEY with the actual key

**Comment by Yuppich** [comment]
> I do not see this issue when using the library versions specified above. Is the OpenAI key provided in override.yaml in this format
> 
> ```
> OpenAI:
>   api_key: 'API_KEY'
> ```
> 
> Replace API_KEY with the actual key

It is. API generated on https://platform.openai.com/api-keys
![image](https://github.com/vivekuppal/transcribe/assets/81874089/ab80d426-26f6-4815-82cd-0824b3e117c5)

**Comment by mang0sw33t** [comment]
Sounds like some other library with the name `openai` is being referenced instead of the intended `openai` library.

share complete output for the command
`pip list`

**Comment by Yuppich** [comment]
> Sounds like some other library with the name `openai` is being referenced instead of the intended `openai` library.
> 
> share complete output for the command `pip list`

Package                   Version
------------------------- -----------
aiohttp                   3.9.3
aiosignal                 1.3.1
altgraph                  0.17.4
annotated-types           0.6.0
anyio                     4.2.0
attrs                     23.2.0
certifi                   2024.2.2
cffi                      1.16.0
charset-normalizer        3.3.2
click                     8.1.7
colorama                  0.4.6
customtkinter             5.2.2
darkdetect                0.8.0
dataclasses-json          0.6.4
deepgram-sdk              3.1.2
distro                    1.9.0
filelock                  3.13.1
frozenlist                1.4.1
fsspec                    2024.2.0
gTTS                      2.5.1
h11                       0.14.0
httpcore                  1.0.2
httpx                     0.26.0
idna                      3.6
Jinja2                    3.1.3
llvmlite                  0.42.0
MarkupSafe                2.1.5
marshmallow               3.20.2
more-itertools            10.2.0
mpmath                    1.3.0
multidict                 6.0.5
mypy-extensions           1.0.0
networkx                  3.2.1
numba                     0.59.0
numpy                     1.24.3
openai                    1.11.1
openai-whisper            20231117
packaging                 23.2
pefile                    2023.2.7
pip                       23.2.1
playsound                 1.2.2
PyAudioWPatch             0.2.12.6
pycparser                 2.21
pydantic                  2.6.1
pydantic_core             2.16.2
pyinstaller               6.3.0
pyinstaller-hooks-contrib 2024.0
pyperclip                 1.8.2
pywin32-ctypes            0.2.2
PyYAML                    6.0.1
regex                     2023.12.25
requests                  2.31.0
setuptools                65.5.0
sniffio                   1.3.0
soundfile                 0.12.1
sympy                     1.12
tiktoken                  0.5.2
torch                     2.2.0+cu121
tqdm                      4.66.1
typing_extensions         4.9.0
typing-inspect            0.9.0
urllib3                   2.2.0
verboselogs               1.7
Wave                      0.0.2
websockets                12.0
yarl                      1.9.4


By the way, thank you for your time!

**Comment by mang0sw33t** [comment]
cannot repro the issue

**Comment by vivekuppal** [comment]
If you are available for a video conferencing call, I am happy to look into the issue on the call.

**Comment by vivekuppal** [comment]
Going through the issue there are a few things in your environment that need to be corrected

1. Path to PowerShell is not set in the system path
    See instructions to set the path correctly - https://www.java.com/en/download/help/path.html
    Path should very likely be set to `C:\WINDOWS\System32\WindowsPowerShell\v1.0\`

2. Path to git is not set in the system path
    See instructions to set the path correctly - https://www.java.com/en/download/help/path.html
    Path should very likely be set to `C:\Program Files\Git\cmd`

**Comment by mang0sw33t** [comment]
PowerShell, git have to be added to path.
Reopen, add comments for any further updates.

**Comment by robinhoodiv** [comment]
Have a similar issue when I first open the exe I get:
[INFO] Using default microphone.
[INFO] Adjusting for ambient noise from Default Mic. Please make some noise from the Default Mic...
[INFO] Completed ambient noise adjustment for Default Mic.
[INFO] Using default speaker.
[INFO] Listening to sound from Speaker: #20 - Speakers (Focusrite Usb Audio) [Loopback]
[INFO] Whisper using GPU: True
fatal: not a git repository (or any of the parent directories): .git

Then:
[INFO] Operating in Desktop mode
READY

Next the UI comes up and when I click "Suggest Response Now":
Exception in thread UpdateResponseUINow:
Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
  File "ui.py", line 109, in update_response_ui_now_threaded
  File "ui.py", line 258, in write_in_textbox
  File "customtkinter\windows\widgets\ctk_textbox.py", line 352, in insert
  File "tkinter\__init__.py", line 3809, in insert
_tkinter.TclError: wrong # args: should be ".!ctktextbox2.!text insert index chars ?tagList chars tagList ...?"

Please let me know what I can try to fix this or if I can supplement any other info to try and diagnose the issue. Thank you.

**Comment by mang0sw33t** [comment]
It seems like you are using the exe and not the code from Github. Please confirm.

@robinhoodiv the issue you are encountering and the original issue in this thread are different. 
See #154, that seems like the issue you are encountering.

Please file a separate issue for what you are encountering.
In the new issue please answer all questions asked in this comment - https://github.com/vivekuppal/transcribe/issues/154#issuecomment-1964590503
