### ISSUE TITLE
Responses are not generating - client side 

### ISSUE THREAD

**Issue by katsie03** [vivekuppal/transcribe#154]
Hello! 

This seems to be a real cool product, however when I complied the application and tried using it, the LLM did not give any responses back even when an example audio was playing for it to respond to - when hitting the "Suggest Response Now", I got this error in the log? Is this just me being an idiot and compiling it incorrectly....? I tried on both Python 3.11.0 & 3.11.5.

Thanks

`Exception in thread UpdateResponseUINow:
Traceback (most recent call last):
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\XXX\Documents\transcribe-main\app\transcribe\ui.py", line 109, in update_response_ui_now_threaded
    write_in_textbox(self.global_vars.response_textbox, response_string)
  File "C:\Users\XXX\Documents\transcribe-main\app\transcribe\ui.py", line 258, in write_in_textbox
    textbox.insert("0.0", text)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_textbox.py", line 352, in insert
    return self._textbox.insert(index, text, tags)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 3808, in insert
    self.tk.call((self._w, 'insert', index, chars) + args)
_tkinter.TclError: wrong # args: should be ".!ctktextbox2.!text insert index chars ?tagList chars tagList ...?"`

**Comment by mang0sw33t** [comment]
Is this unmodified code as it exists in the repo or are there any modifications.
Explain what you mean by compiling the code? Python is not a compiled language.

Confirm API key is correctly provided in the override.yaml file or parameters.yaml file

**Comment by mang0sw33t** [comment]
Potentially resolved in #158

**Comment by mang0sw33t** [comment]
Resolving since no response from user in over 10 days
