### ISSUE TITLE
KeyError: <customtkinter.windows.ctk_toplevel.CTkToplevel object .!ctktoplevel>

### ISSUE THREAD

**Issue by boboboma** [vivekuppal/transcribe#156]
hello,when i open python main.py --api,he LLM did not give any responses back even when an example audio was playing for it to respond to - when hitting the "Suggest Response Now",Here's an error message I encountered. Did I do something wrong? Please help me.
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\86187\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\86187\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 861, in callit
    func(*args)
  File "C:\Users\86187\transcribe\app\transcribe\venv\Lib\site-packages\customtkinter\windows\widgets\scaling\scaling_tracker.py", line 180, in check_dpi_scaling
    if current_dpi_scaling_value != cls.window_dpi_scaling_dict[window]:
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: <customtkinter.windows.ctk_toplevel.CTkToplevel object .!ctktoplevel>
Exception in thread Summarize:
Traceback (most recent call last):
  File "C:\Users\86187\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\86187\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\86187\transcribe\app\transcribe\ui.py", line 119, in summarize_threaded
    summary = self.global_vars.responder.summarize()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86187\transcribe\app\transcribe\gpt_responder.py", line 60, in summarize
    summary_response = self.llm_client.chat.completions.create(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86187\transcribe\app\transcribe\venv\Lib\site-packages\openai\_utils\_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86187\transcribe\app\transcribe\venv\Lib\site-packages\openai\resources\chat\completions.py", line 663, in create
    return self._post(
           ^^^^^^^^^^^
  File "C:\Users\86187\transcribe\app\transcribe\venv\Lib\site-packages\openai\_base_client.py", line 1200, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86187\transcribe\app\transcribe\venv\Lib\site-packages\openai\_base_client.py", line 889, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\Users\86187\transcribe\app\transcribe\venv\Lib\site-packages\openai\_base_client.py", line 980, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'message': 'The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}

**Comment by abhinavuppal1** [comment]
Seems like you do not have access to the gpt4 model.
Read the details of possible reasons for it.
`https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4`

To resolve it
Change the model from gpt-4 to an earlier model. To do that add the following section to `override.yaml` file
    ```
    OpenAI:
       api_key: 'API_KEY'
       ai_model: 'gpt-3.5-turbo-0301'
    ```

**Comment by mang0sw33t** [comment]
Complete output from the command line including the command line used to execute the program is very helpful in diagnosing issues. 
Let us know if you continue to encounter any issues.

**Comment by boboboma** [comment]
i solve my problem!!!!!thank you so much !!!!!

**Comment by mang0sw33t** [comment]
Let us know what steps lead to resolution of the problem for the benefit of the community.
