### ISSUE TITLE
Network Connection Issues and Exceptions When Running Under Proxy Mode with Clash

### ISSUE THREAD

**Issue by Damue01** [vivekuppal/transcribe#166]
[INFO] Using default microphone.
[INFO] Adjusting for ambient noise from Default Mic. Please make some noise from the Default Mic...
[INFO] Completed ambient noise adjustment for Default Mic.
[INFO] Using default speaker.
[INFO] Listening to sound from Speaker: #8 - 扬声器/听筒 (Realtek Audio) [Loopback]
[INFO] Using Open AI Whisper API for transcription.
[INFO] Disabling Speaker
READY
Exception in thread HostConfig:
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 537, in _make_request
  File "urllib3\connection.py", line 466, in getresponse
  File "http\client.py", line 1371, in getresponse
  File "http\client.py", line 318, in begin
  File "http\client.py", line 279, in _read_status
  File "socket.py", line 706, in readinto
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 847, in urlopen
  File "urllib3\util\retry.py", line 470, in increment
  File "urllib3\util\util.py", line 39, in reraise
  File "urllib3\connectionpool.py", line 793, in urlopen
  File "urllib3\connectionpool.py", line 539, in _make_request
  File "urllib3\connectionpool.py", line 370, in _raise_timeout
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=7890): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
  File "interactions.py", line 185, in host_config_loop
  File "requests\api.py", line 73, in get
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 532, in send
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=7890): Read timed out. (read timeout=10)
Connection error.
'str' object has no attribute 'text'

Description:
The application experiences network connection issues, resulting in timeouts and attribute access errors when running under proxy mode with Clash. When switched to direct mode, connection succeeds, but specific functionalities related to speech processing do not work unless the proxy mode is reactivated.

Steps to Reproduce:

Start the application with Clash set to proxy mode.
Observe the application's attempt to adjust for ambient noise and utilize the default microphone and speaker.
Note the application's use of the Open AI Whisper API for transcription and subsequent disabling of the speaker.
Encounter a series of timeout errors and attribute access errors in the application's logs.
Switch Clash to direct mode and restart the application, observing successful connection but limited functionality.
Reactivate proxy mode to restore functionality, noting the recurrence of the previously mentioned errors.
Expected Results:
The application should run seamlessly, connecting to required services and processing speech without encountering network-related errors, irrespective of the network environment setup (proxy or direct mode).

Questions/Requests for Assistance:
Seeking advice on configuring the network environment to prevent these issues while using Clash in proxy mode.

**Comment by j0n0w1ns** [comment]
Are you using a recent version of the application? Are you using source code or pre-built binaries.
Call stack suggests an earlier version of the code.

Cannot see the command line parameters for starting the application. Share the command line parameters.

Are you using opeani services hosted at `https://api.openai.com/v1` or are you using a different openai compatible provider

What is the ping to the `api.openai.com` or the openai compatible service provider when using proxy. I see a ping of under 10ms consistently

```
>ping api.openai.com

Pinging api.openai.com [104.18.7.192] with 32 bytes of data:
Reply from 104.18.7.192: bytes=32 time=8ms TTL=60
Reply from 104.18.7.192: bytes=32 time=7ms TTL=60
Reply from 104.18.7.192: bytes=32 time=11ms TTL=60
Reply from 104.18.7.192: bytes=32 time=7ms TTL=60
```

**Comment by Damue01** [comment]
Application and Version Details
Download Source: Google Drive
Version: 2024-01-30-transcribe
API Used: https://api.openai.com/v1

I can open the openai.com correctly, but when I ping api.openai.com, it failed. maybe that is the point
is there another imformation need i support? I'm trying to solve the net problem
```
Pinging api.openai.com [2a03:2880:f11c:8083:face:b00c:0:25de] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 2a03:2880:f11c:8083:face:b00c:0:25de:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),
```
<details>
<summary> logs </summary>

[INFO] Using default microphone.
[INFO] Adjusting for ambient noise from Default Mic. Please make some noise from the Default Mic...
[INFO] Completed ambient noise adjustment for Default Mic.
[INFO] Using default speaker.
[INFO] Listening to sound from Speaker: #8 - 扬声器/听筒 (Realtek Audio) [Loopback]
[INFO] Using Open AI Whisper API for transcription.
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 537, in _make_request
  File "urllib3\connection.py", line 466, in getresponse
  File "http\client.py", line 1371, in getresponse
  File "http\client.py", line 318, in begin
  File "http\client.py", line 279, in _read_status
  File "socket.py", line 706, in readinto
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 847, in urlopen
  File "urllib3\util\retry.py", line 470, in increment
  File "urllib3\util\util.py", line 39, in reraise
  File "urllib3\connectionpool.py", line 793, in urlopen
  File "urllib3\connectionpool.py", line 539, in _make_request
  File "urllib3\connectionpool.py", line 370, in _raise_timeout
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=7890): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 114, in <module>
  File "main.py", line 51, in main
  File "args.py", line 90, in handle_args_batch_tasks
  File "interactions.py", line 86, in params
  File "requests\api.py", line 73, in get
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 532, in send
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=7890): Read timed out. (read timeout=10)
[5692] Failed to execute script 'main' due to unhandled exception!

</details>

**Comment by Damue01** [comment]
hey, I get a different openai api forward, could u tell me where should I replace the original api?
here is it:
from openai import OpenAI
client = OpenAI(
    base_url="https://xxxxxxxxxxx"
      + ".api-forwards.com/v1",
    api_key=" API Key"
)

**Comment by j0n0w1ns** [comment]
problem solved :-) 
GREAT!
