### ISSUE TITLE
Responses not generating

### ISSUE THREAD

**Issue by robinhoodiv** [vivekuppal/transcribe#171]
Have an issue when I first open the exe I get:
[INFO] Using default microphone.
[INFO] Adjusting for ambient noise from Default Mic. Please make some noise from the Default Mic...
[INFO] Completed ambient noise adjustment for Default Mic.
[INFO] Using default speaker.
[INFO] Listening to sound from Speaker: https://github.com/vivekuppal/transcribe/pull/20 - Speakers (Focusrite Usb Audio) [Loopback]
[INFO] Whisper using GPU: True
fatal: not a git repository (or any of the parent directories): .git

Then:
[INFO] Operating in Desktop mode
READY

Next the UI comes up and when I click "Suggest Response Now":
Exception in thread UpdateResponseUINow:
Traceback (most recent call last):
File "threading.py", line 1038, in bootstrap_inner
File "threading.py", line 975, in run
File "ui.py", line 109, in update_response_ui_now_threaded
File "ui.py", line 258, in write_in_textbox
File "customtkinter\windows\widgets\ctk_textbox.py", line 352, in insert
File "tkinter_init.py", line 3809, in insert
_tkinter.TclError: wrong # args: should be ".!ctktextbox2.!text insert index chars ?tagList chars tagList ...?"

I haven’t touched the code I simply followed the instructions on the GitHub page without the optional step of adding a API key. The files I downloaded are from the google drive and then just unzipped them and opened the exe.

Please let me know what I can try to fix this or if I can supplement any other info to try and diagnose the issue. Thank you.

**Comment by vivekuppal** [comment]
Appreciate filing a clear explanation of what happened.
I am able to reproduce the issue with the steps outlined above.

Observations
- Transcription is showing in the application as expected.
- No visible errors in the application UI.
- Error as described in the issue description is visible in the command window.

From a functional perspective, application is behaving as it should.
Without an API key it is expected that user will not be able to get a response from backend services and that is what is happening.

There is a potential improvement to user interface behavior to improve this scenario from user perspective
- When API key is not specified or is invalid, UI widgets which should not function should show as disabled or something else so the action cannot be triggered by user
OR
- A better error message is displayed to the end user so the issue is clearly evident

Expectation is that if API key is specified, this situation will not occur, and application will be able to retrieve responses from backend services.

Let us know if this provides adequate explanation for the behavior.

**Comment by robinhoodiv** [comment]
Will try plugging in my openai API key when I get back to my windows computer at home to see if that works. But think I tried that before and got a different error. 

Will report back.

**Comment by robinhoodiv** [comment]
Ok, I have inputted in an API Key. The startup messages in the command window remain the same.

But, now, when I click the "Suggest Response Now" button in the UI the command window gives me this error:

Error when attempting to get a response from LLM.
Error code: 404 - {'error': {'message': 'The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}

The only thing I have changed is inputting my openai api key in the override.yaml files as described:
![image](https://github.com/vivekuppal/transcribe/assets/54639631/35824614-d962-49dc-9e45-e94b58bd2702)

**Comment by robinhoodiv** [comment]
I have access to GPT-4... so not sure why this would be an issue.

However I have also tried https://github.com/vivekuppal/transcribe/issues/156#issuecomment-1971051009

To attempt at using GPT 3.5 instead...

But, when I add that section into the override.yaml file I get another error and the LLM again does not provide a response in the UI and gives this error in the command prompt:
Error when attempting to get a response from LLM.
Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

This despite my thinking that GPT 3.5 didn't have quota limits...

Please let me know.

**Comment by vivekuppal** [comment]
I am assuming you are using openai and not an alternate provider.

openai has moved to a pre-paid billing model. They want users to buy credits before users can use the service. I suspect you have not bought any credits as yet, resulting in the errors.
Credits can be bought at this location - https://platform.openai.com/account/billing/overview

**Comment by vivekuppal** [comment]
Do let us know if the issue is resolved. Always happy to help.
