### ISSUE TITLE
plz help me Operating as a standalone client [INFO] Adjusting for ambient noise from Default Mic. Please make some noise from the Default Mic... [INFO] Completed ambient noise adjustment for Default Mic. [INFO] Adjusting for ambient noise from Default Speaker. Please make or play some noise from the Default Speaker... [INFO] Completed ambient noise adjustment for Default Speaker. Using Open AI API for transcription. READY Traceback (most recent call last):   File "C:\Users\Saira\transcribe\main.py", line 131, in <module>     main()   File "C:\Users\Saira\transcribe\main.py", line 121, in main     lang_combobox.configure(command=model.change_lang)                                     ^^^^^^^^^^^^^^^^^ AttributeError: 'APIWhisperTranscriber' object has no attribute 'change_lang'

### ISSUE THREAD

**Issue by sairaghavaa** [vivekuppal/transcribe#23]
Operating as a standalone client
[INFO] Adjusting for ambient noise from Default Mic. Please make some noise from the Default Mic...
[INFO] Completed ambient noise adjustment for Default Mic.
[INFO] Adjusting for ambient noise from Default Speaker. Please make or play some noise from the Default Speaker...
[INFO] Completed ambient noise adjustment for Default Speaker.
Using Open AI API for transcription.
READY
Traceback (most recent call last):
  File "C:\Users\Saira\transcribe\main.py", line 131, in <module>
    main()
  File "C:\Users\Saira\transcribe\main.py", line 121, in main
    lang_combobox.configure(command=model.change_lang)
                                    ^^^^^^^^^^^^^^^^^
AttributeError: 'APIWhisperTranscriber' object has no attribute 'change_lang'

**Comment by sairaghavaa** [comment]
this my number ls contact me i want a help from you i will pay for that if needed
+916302151545
ig:sairaghava143
mail:sairaghava430@gmail.com

**Comment by vivekuppal** [comment]
I am looking into the issue, I should have a PR up to resolve this soon.
If you wish to help, it would be great to get stars on the github repo and some word of mouth (twitter, online forums) publicity for the same.

**Comment by vivekuppal** [comment]
I believe the issue is resolved now. Please update code to latest and confirm.

**Comment by sairaghavaa** [comment]
Bro please give me your contact details or mail id I want a custom interview breaker like this ( https://twitter.com/localghost/status/1640448469285634048?t=q2lpQC3mwmeepWa-HlQMcQ&s=19 ). Please contact me let's discuss further

**Comment by vivekuppal** [comment]
Sent you a response at the contact info mentioned above. Lets discuss there

**Comment by sairaghavaa** [comment]
sir ,i did't get any response yet.

**Comment by vivekuppal** [comment]
The original issue as reported has been resolved. We are looking into enhancement requests as a separate conversation.
